### ISSUE TITLE
Library problem during LINUX installation

### ISSUE THREAD

**Issue by sagnickm** [tomasstolker/ARTES#1]
I was trying to install the code but the make file procedure was failing again and again as the 'ld' couldn't find the cfitsio library despite it being downloaded everytime with wget. Then I realised that 'libcfitsio.so.3' was being downloaded with wget but the code was perhaps looking for 'libcfitsio.so' so I did 'ln libcfitsio.so.3 libcfitsio.so' and then the 'make' command ran smoothly. I am not sure if this is my computer specific problem. But thought I should let the developers know about this.

**Comment by tomasstolker** [comment]
Thanks for reporting this issue!

I briefly tested on Mac and Linux, but I can not reproduce the error. Did you ran the installation on linux as `make all linux=true`? This is required to point to the correct `cfitsio` library.

Otherwise, could you provide a few more details on how you ran the `Makefile` and what error you got?

**Comment by sagnickm** [comment]
Hi ! 
Sorry for the late response.
I went through the exact instruction steps for running the makefile as the documentation page had except it could not find the library. I did do 'make all linux=true' while installing. Somehow it was just a renaming issue which fixed the problem as I mentioned earlier. The code is up and running succesfully now. I think it was a computer specific issue.

I have another question for you. I was trying to run the 'dhs' module of opacity.py to generate the cloud optics file for a run.
The input file is a txt file with first col:wavelength, second col: real refractive index and third col: imaginary refractive index. I have also specified the wavelength range as an input to the dhs module in opacity.py. The code is running upto the line `os.rename(temp_dir+"particle.fits", output)` and then is saying that it cannot find this 'particle.fits' file. I physically checked the temp folder being created which has a wavelength and a mie file but lacks a file by this name. Can you please tell me what is this file exactly? Am I doing something wrong in this method? The command I am running to run the code is 
`python ../ARTES-master/tools/opacity.py dhs '../../second_try/Al2O3'`
The error is 
```
 File "../ARTES-master/tools/opacity.py", line 923, in <module>
    opacity_dhs(sys.argv[2])
  File "../ARTES-master/tools/opacity.py", line 532, in opacity_dhs
    os.rename(temp_dir+"particle.fits", output)
FileNotFoundError: [Errno 2] No such file or directory: 'temp/particle.fits' -> 'dhs.fits'

```
And my dhs module looks like
```
def opacity_dhs(ri_file,
                wavelength=(0.5,5,10),
                output="dhs.fits",
                nr=100,
                nf=20,
                density=1.,
                amin=0.1,
                amax=1.0,
                apow=3.5,
                fmax=0.,
                r_eff=1.0,
                v_eff=0.1):
```
Sorry for asking this in this same thread.

**Comment by tomasstolker** [comment]
Thanks for pointing that out! There was an issue with the use of ``os.chmod`` in ``opacity.py`` so the permissions of the ``computepart`` file were not correctly set.

I fixed the bug and also did some minor maintenance so please update your local copy of ``ARTES`` (e.g. with ``git pull``).

The ``opacity`` functions were not so well documented so I have added some details here:
https://artes.readthedocs.io/en/latest/opacity.html

Does that help solving your problem with running ``opacity_dhs``?

Let me know if you have any other questions.

**Comment by sagnickm** [comment]
Thanks for this update. Yes the new version did fix the `opacity_dhs` problem. The documentation on this is really helpful thank you for that. I did some initial successful runs and have some other confusions as well (listed).

1. I did some runs with the oblateness parameter set to 0 in the `artes.in` file. This gave me beautiful images after running the `plot_image.py` tool. But keeping everything else the same and setting the oblateness to 0.1 (or any other non zero value) is always producing blank images with the `plot_image.py`tool. I am not really sure why is this happening? I am attaching two 'I images' produced by the same `artes.in` and` atmosphere.in` and opacity files just differing in the oblateness param. The good one is 0 and the blank one is 0.1.

2. When I run `./../ARTES-master/bin/artes artes.in 1e6 -o destination_folder` it prints out a set of parameters like radius and stuff used for the calculation. I saw that even if the `artes.in` has `photon:source=planet` , the terminal always says the photon source to be star with some properties. I am a bit confused with this. Also while I want the mode to be `imaging` the wavelength is printed to be 0.2 microns. How do I change this wavelength parameter?

Thank you for your help regarding these issues. This has been really helpful.

[image_i.pdf](https://github.com/tomasstolker/ARTES/files/5146423/image_i.pdf)
[image_i.pdf](https://github.com/tomasstolker/ARTES/files/5146424/image_i.pdf)

**Comment by tomasstolker** [comment]
> I did some runs with the oblateness parameter set to 0 in the artes.in file. This gave me beautiful images after running the plot_image.py tool. But keeping everything else the same and setting the oblateness to 0.1 (or any other non zero value) is always producing blank images with the plot_image.pytool. I am not really sure why is this happening? I am attaching two 'I images' produced by the same artes.in and atmosphere.in and opacity files just differing in the oblateness param. The good one is 0 and the blank one is 0.1.

Is the simulation in reflected light or thermal emission from the planet? Currently, an oblateness > 0 is only support by thermal emission (i.e. `photon:source=planet`).

Or could it be that the bright pixel is simply Monte Carlo noise? Is the planet visible if you adjust the colorbar of the image? By default the colorbar is set by the dynamical range of the image pixels, but you may have to adjust it. Using a larger number of photons should reduce the noise. You could also have a look at the FITS files in the output folder, for example with the DS9 software.

> When I run ./../ARTES-master/bin/artes artes.in 1e6 -o destination_folder it prints out a set of parameters like radius and stuff used for the calculation. I saw that even if the artes.in has photon:source=planet , the terminal always says the photon source to be star with some properties. I am a bit confused with this. Also while I want the mode to be imaging the wavelength is printed to be 0.2 microns. How do I change this wavelength parameter?

If `photon:source=planet` then it should say `Photon source: planet` in the log file, is that not the case?

There might be some stellar properties printed to the output, which should indeed be hidden, but these parameters are not used if `photon:source=planet`.

For the wavelengths, `ARTES` uses the wavelengths from the opacity files. So with `detector:type=imaging` it will simply select the first wavelength from these files, so you have to make sure that the same wavelengths are used in the different opacities values. I will add a not to the documentation because I realize that this is not so obvious.

Let me know if you have any other questions. If so, could you share the file with input parameters and the log file (make sure to set `general:log=on`)? That will make it easier for me to understand what is the problem.

**Comment by sagnickm** [comment]
Hi !
Thank you ! Each of these comments helped me a lot and now I think the code is behaving as expected for me. The problem with oblateness I discovered was due to writing `photon:source= planet` instead of `photon:source=planet` which caused the code to think that I am using star as a source and hence the wrong log file message and the problem with oblateness. Now it is running properly for non-zero oblateness and also printing out planet as the source in the log.

I just had another clarification question.

Say my T(P) file looks like

```
#Pressure(bars) Temperature (K)
1.778299999999999965e-04 3.256999999999999886e+02
2.049800000000000059e-04 3.268000000000000114e+02
2.362800000000000078e-04 3.283999999999999773e+02
2.723499999999999793e-04 3.301999999999999886e+02

```
and I want to add a cloud layer between the 2nd and 3rd Pressure points. Then will this line in the atmosphere.in file work?
```
; FITS number, density [g cm-3], rIn, rOut, thetaIn, thetaOut, phiIn, phiOut
opacity01: 1, 1e-5, 3, 2, 0, ntheta, 0, nphi
```
or do I need to do this ?
```
[grid]
radial: 3e4,4e4
opacity01: 1, 1e-5, 1, 2, 0, ntheta, 0, nphi
```
where 3e4 and 4e4 are say radius in km corresponding to those two pressure points?
Also, thank you for helping me through the code.

**Comment by tomasstolker** [comment]
When providing a P/T profile, the radial grid boundaries are calculated when running ``tools/atmosphere.py``, so your first solution is indeed what is required (i.e. no values of `radial` should be provided, but `theta` and `phi` can still be used for horizontal structures).

However, `rIn` and `rOut` should be provided by counting from the innermost radius. For example,

`opacity01: 1, 1e-5, 0, 1, 0, ntheta, 0, nphi`

will put the clouds between the innermost and first radial grid boundary.

At least, I am quite sure this is how it was setup but it is already a while ago since I used it myself...

Thanks for your feedback, I will add a few more details in the documentation to clarify these things.

**Comment by sagnickm** [comment]
Hi !
I had another question. If I run with  `detector:type=spectrum` set in artes.in, I get a file called "spectrum.dat" with the wavelength dependent stokes parameters in it. I am running for thermal emission. Are these parameters in this mode disk integrated ?

**Comment by tomasstolker** [comment]
Yes exactly, these are the disk-integrated fluxes.
